---
# Tasks: bookstack
#
# Author: bitfinity-nl
# File: tasks/main.yml
# 
# Description:
#   BookStack is a simple, self-hosted, easy-to-use 
#   platform for organising and storing information.
#
    
- name: "Type:bookstack, For OS: Ubuntu 18.04LTS, Arch: amd64, State: Enabled"
  import_tasks: ubt-1804-amd64.yml
  when:
    - ansible_distribution_version == '18.04'
    - ansible_architecture == 'x86_64'


 - name: "Type:bookstack, For OS: Ubuntu 16.04LTS, Arch: amd64, State: Enabled"
   import_tasks: ubt-1604-amd64.yml
   when:
     - ansible_distribution_version == '16.04'
     - ansible_architecture == 'x86_64'
