---
  # Tasks: BookStack
  #
  # Author: Luc Rutten
  # Version: 1.0

  - name: "Install packages"
    apt:
      name: "{{ item }}"
      update_cache: yes
      state: present
    with_items:
      - zip
      - unzip
      - git
      - nginx
      - curl
      - php7.0-fpm
      - php7.0-curl
      - php7.0-mbstring
      - php7.0-ldap
      - php7.0-mcrypt
      - php7.0-tidy
      - php7.0-xml
      - php7.0-zip
      - php7.0-gd
      - php7.0-mysql
      - mcrypt

  - name: "Create initial BookStack MySQL database"
    mysql_db:
      name: "{{ bst_dbname }}"
      encoding: utf8
      state: present
      login_user: "{{ MySQL_ROOT_ACCOUNT }}"
      login_password: "{{ MySQL_ROOT_PASSWORD }}"

  - name: "Create BookStack MySQL database user"
    mysql_user:
      name: "{{ bst_dbuser }}"
      password: "{{ bst_dbpass }}"
      priv: "{{ bst_dbname }}.*:ALL,GRANT"
      state: present
      login_user: "{{ MySQL_ROOT_ACCOUNT }}"
      login_password: "{{ MySQL_ROOT_PASSWORD }}"

  - name: "Download BookStack from git"
    git:
      repo: 'https://github.com/BookStackApp/BookStack.git'
      dest: {{ bst_dir }}
      update: no

  - name: "Download template composer script"
    template:
      src: install_composer.sh.j2
      dest: /home/ansible/install_composer.sh
      owner: ansible
      group: sudo
      mode: 0755

  - name: "Set file and folder permissions"
    file:
      path:  {{ bst_dir }}/bootstrap/cache public/uploads storage
      owner: www-data
      group: www-data
      mode: 0755
      recurse: yes
      state: directory

  - name: "Excecute template /opt/install_composer.sh"
    shell: /home/ansible/install_composer.sh
    #become: true
    #become_method: su
    #become_user: ansible

