---
# Tasks: bookstack
#
# Author: bitfinity-nl
# File: handlers/main.yml
# 
# Description:
#   BookStack is a simple, self-hosted, easy-to-use 
#   platform for organising and storing information.
#

- name: restart_nginx
  service:
    name: nginx
    state: restarted
